# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [359]:
import numpy as np

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [360]:
arr = np.random.uniform(0, 20, size=(4, 7))
(arr - arr.min())/ (arr.max() - arr.min())

array([[0.6837713 , 0.27759763, 0.64396295, 0.90279723, 0.31055782,
        0.58271502, 0.49519343],
       [0.99049118, 0.        , 0.65304113, 0.86609294, 0.05964716,
        0.65503262, 0.43616636],
       [0.92061026, 0.26473932, 0.26508815, 0.28968327, 1.        ,
        0.68815591, 0.63883601],
       [0.5372338 , 0.45079064, 0.60999787, 0.90378416, 0.70675447,
        0.53779564, 0.3753782 ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [361]:
matrix = np.random.random_integers(0, high=10, size=(8, 10))
matrix

C:\Users\damir\AppData\Local\Temp/ipykernel_15352/3486773722.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  matrix = np.random.random_integers(0, high=10, size=(8, 10))


array([[10, 10,  5,  3,  3,  8,  1,  4,  1,  3],
       [ 2,  5,  2,  4,  5,  7,  7,  0,  0,  3],
       [ 5,  9,  5,  7,  8,  3,  9,  6,  9,  0],
       [ 9,  3,  6,  4,  6,  7,  4,  1,  5,  2],
       [ 0,  6,  9,  6,  0,  9,  3,  3,  4,  9],
       [ 4,  3,  4,  9,  8,  8,  8,  7,  7,  8],
       [ 7,  3,  4, 10,  1,  4,  4,  6,  8, 10],
       [ 2,  6, 10,  9,  4,  6,  1,  5,  1,  9]])

In [362]:
sum_of_rows = matrix.sum(axis=1)

print(np.argmin(sum_of_rows))
matrix[np.argmin(sum_of_rows)]

1


array([2, 5, 2, 4, 5, 7, 7, 0, 0, 3])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [363]:
vector1 = np.random.rand(3,1)
vector1

array([[0.25822861],
       [0.00488667],
       [0.52983048]])

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [364]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
minus_C = C * -1
transpose_A = np.transpose(A)
transpose_B = np.transpose(B)
out = transpose_A @ minus_C @ transpose_B
out

array([[ 135,  185],
       [ -25, -100],
       [ -70, -220]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

In [365]:
arr = np.loadtxt("data/minutes_n_ingredients.csv", dtype='int32', skiprows=1, delimiter=",")
print(arr[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [366]:
mean = np.mean(arr, axis=0)
print(mean)

minimum = arr.min(axis=0)
print(minimum)

maximum = arr.max(axis=0)
print(maximum)

median = np.median(arr, axis=0)
print(median)

[2.22064324e+05 2.16010017e+04 9.05528000e+00]
[38  0  1]
[    537671 2147483647         39]
[2.071935e+05 4.000000e+01 9.000000e+00]


 3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [367]:
quantile = np.quantile(arr[:, 1], .75)
arr[:, 1] = np.where(arr[:, 1] > quantile, quantile, arr[:, 1])
arr

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [368]:
print(np.sum(arr[:, 1:2] == 0))

arr[:, 1:2][arr[:, 1:2] == 0] = 1
arr

479


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [369]:
# np.count_nonzero(arr[:, :1])
np.shape(arr)[0]

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [370]:
values, counts = np.unique(arr, return_counts=True)
print(values, counts)

[     1      2      3 ... 537458 537485 537671] [ 729 1738 3358 ...    1    1    1]


 7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [371]:
arr_copy_lower_then5 = arr.copy()
mask = arr_copy_lower_then5[:, 2] <= 5
arr_copy_lower_then5[mask]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [372]:
arr_copy = arr.copy().astype(np.float32)
values = arr_copy[:, 2] / arr_copy[:, 1]
arr_copy = np.insert(arr_copy, 3, values, axis = 1)
arr_copy

array([[1.2724400e+05, 6.0000000e+01, 1.6000000e+01, 2.6666668e-01],
       [2.3891000e+04, 2.5000000e+01, 7.0000000e+00, 2.8000000e-01],
       [9.4746000e+04, 1.0000000e+01, 6.0000000e+00, 6.0000002e-01],
       ...,
       [4.9843200e+05, 6.5000000e+01, 1.5000000e+01, 2.3076923e-01],
       [3.7091500e+05, 5.0000000e+00, 4.0000000e+00, 8.0000001e-01],
       [8.1993000e+04, 6.5000000e+01, 1.4000000e+01, 2.1538462e-01]],
      dtype=float32)

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [373]:
np.mean(arr[arr[:, 1].argsort()][-100:, :], axis=0)[2]

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [374]:
arr[np.random.randint(len(arr), size=10)]

array([[398786,     65,      9],
       [151824,     45,     14],
       [487052,     43,     12],
       [224940,     65,     17],
       [ 57512,     25,      5],
       [217844,     65,     12],
       [135876,     20,      7],
       [112636,     35,      7],
       [311026,     65,      7],
       [207671,     20,     12]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [375]:
(np.count_nonzero(arr[:, 2:3] < np.mean(arr, axis=0)[2]) / len(arr)) * 100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [376]:
arr_copy = arr.copy()
arr_copy = np.c_[ arr_copy, np.zeros(len(arr_copy), dtype=int)]
condition = (arr_copy[:, 1:2] <= 20) & (arr_copy[:, 2:3] <= 5)
arr_copy[:, 3:4] = np.where(condition, 1, arr_copy[:, 3:4])
arr_copy

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [395]:
f"{round(np.sum(arr_copy[:, 3:4])/len(arr_copy), 3) * 100}%"

'9.6%'

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [378]:
arr

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

In [379]:
# lst = [0, 1, 2, 5, 10, 47, 92]
# lst
#

In [380]:
# arr = np.array(lst)
#

In [381]:
# # np.where(arr[])
#

In [382]:
# arr
#

In [383]:
# mask = arr % 5 == 0
# arr[mask]
#

In [384]:
# b = np.array([0,1,2,2,0,1]) # берет элементы с индексом 0, 1, 2, 2, 0, 1 из списка arr
# arr[b]
#

In [385]:
# test_arr = np.arange(20).reshape(5, 4)
# np.transpose(test_arr)
#

In [386]:
# test_arr[:, :1]
#

In [387]:
# test_arr = np.array(lst)
# test_arr%5
#

In [388]:
# mask = arr[:, 2:3] <= 5
# # mask.shape
# # arr[:, :, mask]
# # print(mask)
# masked = arr.copy()
# # masked[:, mask]
# # masked[mask]
# # mask = np.c_[np.ones(100000), np.ones(100000), mask]
# print(mask)
# # masked[np.array(mask)]
# masked
