# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [381]:
import numpy as np

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [382]:
arr = np.random.uniform(0, 20, size=(4, 7))
(arr - arr.min())/ (arr.max() - arr.min())

array([[0.04556875, 0.74224571, 0.01526012, 0.4677771 , 0.3063491 ,
        0.91807075, 0.32500187],
       [0.42954932, 0.87637832, 0.527023  , 0.40209626, 0.969606  ,
        0.08830515, 0.57313876],
       [1.        , 0.48624227, 0.        , 0.78046852, 0.61435481,
        0.43533039, 0.80149652],
       [0.76224843, 0.74219412, 0.37510545, 0.212405  , 0.23090496,
        0.74554664, 0.08385802]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [383]:
matrix = np.random.random_integers(0, high=10, size=(8, 10))
matrix

C:\Users\damir\AppData\Local\Temp/ipykernel_2652/3486773722.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  matrix = np.random.random_integers(0, high=10, size=(8, 10))


array([[ 7,  5,  7,  2,  0, 10,  4,  4,  1,  6],
       [ 6,  8,  5,  2,  6,  5,  5,  0, 10,  1],
       [ 5,  0,  0,  8,  1,  0,  2,  2,  5,  5],
       [ 4,  3,  1,  6,  3,  1,  9,  5,  0,  7],
       [ 8,  3,  0, 10,  1,  8,  0,  3,  7,  8],
       [ 7,  5,  9,  4,  9,  2,  1,  6,  9, 10],
       [ 3,  9,  0,  0,  4,  6,  7,  1,  0,  1],
       [ 6,  7,  8,  8,  5,  3,  2,  1,  4,  6]])

In [384]:
sum_of_rows = matrix.sum(axis=1)

print(np.argmin(sum_of_rows))
matrix[np.argmin(sum_of_rows)]

2


array([5, 0, 0, 8, 1, 0, 2, 2, 5, 5])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [385]:
vector1 = np.random.rand(3,1)
vector1

array([[0.09143115],
       [0.79869825],
       [0.70775317]])

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [386]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
minus_C = C * -1
transpose_A = np.transpose(A)
transpose_B = np.transpose(B)
out = transpose_A @ minus_C @ transpose_B
out

array([[ 135,  185],
       [ -25, -100],
       [ -70, -220]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

In [387]:
arr = np.loadtxt("data/minutes_n_ingredients.csv", dtype='int32', skiprows=1, delimiter=",")
print(arr[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [388]:
mean = np.mean(arr, axis=0)
print(mean)

minimum = arr.min(axis=0)
print(minimum)

maximum = arr.max(axis=0)
print(maximum)

median = np.median(arr, axis=0)
print(median)

[2.22064324e+05 2.16010017e+04 9.05528000e+00]
[38  0  1]
[    537671 2147483647         39]
[2.071935e+05 4.000000e+01 9.000000e+00]


 3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [389]:
quantile = np.quantile(arr[:, 1], .75)
arr[:, 1] = np.where(arr[:, 1] > quantile, quantile, arr[:, 1])
arr

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [390]:
print(np.sum(arr[:, 1:2] == 0))

arr[:, 1:2][arr[:, 1:2] == 0] = 1
arr

479


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [391]:
# np.count_nonzero(arr[:, :1])
np.shape(arr)[0]

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [392]:
values, counts = np.unique(arr, return_counts=True)
print(values, counts)

[     1      2      3 ... 537458 537485 537671] [ 729 1738 3358 ...    1    1    1]


 7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [393]:
arr_copy_lower_then5 = arr.copy()
mask = arr_copy_lower_then5[:, 2] <= 5
arr_copy_lower_then5[mask]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [394]:
arr_copy = arr.copy().astype(np.float32)
values = arr_copy[:, 2] / arr_copy[:, 1]
arr_copy = np.insert(arr_copy, 3, values, axis = 1)
arr_copy

array([[1.2724400e+05, 6.0000000e+01, 1.6000000e+01, 2.6666668e-01],
       [2.3891000e+04, 2.5000000e+01, 7.0000000e+00, 2.8000000e-01],
       [9.4746000e+04, 1.0000000e+01, 6.0000000e+00, 6.0000002e-01],
       ...,
       [4.9843200e+05, 6.5000000e+01, 1.5000000e+01, 2.3076923e-01],
       [3.7091500e+05, 5.0000000e+00, 4.0000000e+00, 8.0000001e-01],
       [8.1993000e+04, 6.5000000e+01, 1.4000000e+01, 2.1538462e-01]],
      dtype=float32)

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [395]:
np.mean(arr[arr[:, 1].argsort()][-100:, :], axis=0)[2]

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [396]:
arr[np.random.randint(len(arr), size=10)]

array([[330246,     65,     10],
       [102544,     35,     10],
       [ 12846,     15,      8],
       [514340,     60,     11],
       [145560,     10,     11],
       [516517,     65,      5],
       [439472,     10,      9],
       [332710,     50,     10],
       [213987,     35,     10],
       [293770,     13,      9]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [397]:
(np.count_nonzero(arr[:, 2:3] < np.mean(arr, axis=0)[2]) / len(arr)) * 100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [398]:
arr_copy = arr.copy()
arr_copy = np.c_[ arr_copy, np.zeros(len(arr_copy), dtype=int)]
condition = (arr_copy[:, 1:2] <= 20) & (arr_copy[:, 2:3] <= 5)
arr_copy[:, 3:4] = np.where(condition, 1, arr_copy[:, 3:4])
arr_copy

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [399]:
f"{round(np.sum(arr_copy[:, 3:4])/len(arr_copy), 3) * 100}%"

'9.6%'

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [400]:

arr_copy = arr.copy()
arr_copy = np.insert(arr_copy, 3, 0, axis = 1)
arr_copy[:, 3][arr_copy[:, 1] < 10] = 0
condition = (10 <= arr_copy[:, 1]) & (arr_copy[:, 1] < 20)
arr_copy[:, 3][condition] = 1
arr_copy[:, 3][arr_copy[:, 1] > 20] = 2
arr_copy


test_arr = np.zeros(100008)
C = test_arr.reshape(11112, 3, 3)
C[0:100008, arr_copy[:, 3], :] = arr_copy[:, 0:3]
C


# new_array = np.array()
# arr[:, 1:2][arr[:, 1:2] == 0] = 1

array([[[3.70915e+05, 5.00000e+00, 4.00000e+00],
        [1.28811e+05, 1.50000e+01, 4.00000e+00],
        [8.19930e+04, 6.50000e+01, 1.40000e+01]],

       [[3.70915e+05, 5.00000e+00, 4.00000e+00],
        [1.28811e+05, 1.50000e+01, 4.00000e+00],
        [8.19930e+04, 6.50000e+01, 1.40000e+01]],

       [[3.70915e+05, 5.00000e+00, 4.00000e+00],
        [1.28811e+05, 1.50000e+01, 4.00000e+00],
        [8.19930e+04, 6.50000e+01, 1.40000e+01]],

       ...,

       [[3.70915e+05, 5.00000e+00, 4.00000e+00],
        [1.28811e+05, 1.50000e+01, 4.00000e+00],
        [8.19930e+04, 6.50000e+01, 1.40000e+01]],

       [[3.70915e+05, 5.00000e+00, 4.00000e+00],
        [1.28811e+05, 1.50000e+01, 4.00000e+00],
        [8.19930e+04, 6.50000e+01, 1.40000e+01]],

       [[3.70915e+05, 5.00000e+00, 4.00000e+00],
        [1.28811e+05, 1.50000e+01, 4.00000e+00],
        [8.19930e+04, 6.50000e+01, 1.40000e+01]]])

In [424]:
# arr_copy = arr.copy()
# new_array = np.zeros((3, 100000, 4))
# new_array[0][0][0] = 1
# new_array[0][1][0] = 2
# new_array[0][2][0] = 3
# new_array[0][3][0] = 4

# new_array
# # (8334, 4, 3)

test_arr = np.zeros(100008)
C = test_arr.reshape(11112, 3, 3)
# C[0:50, arr_copy[:, 3]] = arr_copy[:, 0:3]
C[0:2, 1] = 1
print(C)
# C


# arr_copy[:, 0:3]
# arr_copy[:, :]
# lst = [0, 1, 2, 5, 10, 47, 92]
# lst
#

[[[0. 0. 0.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [402]:
# arr = np.array(lst)
#

In [403]:
# # np.where(arr[])
#

In [404]:
# arr
#

In [405]:
# mask = arr % 5 == 0
# arr[mask]
#

In [406]:
# b = np.array([0,1,2,2,0,1]) # берет элементы с индексом 0, 1, 2, 2, 0, 1 из списка arr
# arr[b]
#

In [407]:
# test_arr = np.arange(20).reshape(5, 4)
# np.transpose(test_arr)
#

In [408]:
# test_arr[:, :1]
#

In [409]:
# test_arr = np.array(lst)
# test_arr%5
#

In [410]:
# mask = arr[:, 2:3] <= 5
# # mask.shape
# # arr[:, :, mask]
# # print(mask)
# masked = arr.copy()
# # masked[:, mask]
# # masked[mask]
# # mask = np.c_[np.ones(100000), np.ones(100000), mask]
# print(mask)
# # masked[np.array(mask)]
# masked
