# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [2]:
import numpy as np

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [173]:
arr = np.random.uniform(0, 20, size=(4, 7))
(arr - arr.min())/ (arr.max() - arr.min())

array([[0.00494535, 0.63404354, 0.19853778, 0.29414265, 0.55430148,
        0.99777554, 0.50742509],
       [0.13214359, 0.6471861 , 0.34487658, 0.47907766, 0.71443385,
        0.98763355, 1.        ],
       [0.94222447, 0.80641088, 0.56112174, 0.62494329, 0.87039511,
        0.91196934, 0.19791158],
       [0.80161366, 0.        , 0.415849  , 0.0330437 , 0.648121  ,
        0.30230705, 0.20390534]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [71]:
matrix = np.random.random_integers(0, high=10, size=(8, 10))
matrix

<ipython-input-71-fc2d14436fcc>:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  matrix = np.random.random_integers(0, high=10, size=(8, 10))


array([[ 6,  8,  1,  2,  8,  5,  3,  4,  7,  5],
       [ 2,  7,  9,  0,  1,  6,  3,  8,  3,  9],
       [ 3,  9, 10,  3,  6,  8,  2,  8,  6,  4],
       [ 0,  8,  4,  8,  2,  3,  4,  0, 10,  3],
       [ 2, 10, 10, 10, 10, 10,  4,  8,  3,  3],
       [ 6,  2,  4,  5,  8,  5,  2, 10,  7,  3],
       [ 7, 10, 10,  5,  5, 10, 10,  3,  2,  0],
       [ 8,  2,  9,  9,  2,  1,  9,  0, 10,  6]])

In [84]:
sum_of_rows = matrix.sum(axis=1)

print(np.argmin(sum_of_rows))
matrix[np.argmin(sum_of_rows)]

3


array([ 0,  8,  4,  8,  2,  3,  4,  0, 10,  3])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [101]:
vector1 = np.random.rand(3,1)
vector1

array([[0.05108107],
       [0.46835362],
       [0.18231716]])

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [8]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
minus_C = C * -1
transpose_A = np.transpose(A)
transpose_B = np.transpose(B)
out = transpose_A @ minus_C @ transpose_B
out

ValueError: output array is not acceptable (must have the right datatype, number of dimensions, and be a C-Array)

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

In [3]:
arr = np.loadtxt("data/minutes_n_ingredients.csv", dtype='int32', skiprows=1, delimiter=",")
print(arr[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [25]:
mean = np.mean(arr, axis=0)
print(mean)

minimum = arr.min(axis=0)
print(minimum)

maximum = arr.max(axis=0)
print(maximum)

median = np.median(arr, axis=0)
print(median)

[2.22064324e+05 2.16010017e+04 9.05528000e+00]
[38  0  1]
[    537671 2147483647         39]
[2.071935e+05 4.000000e+01 9.000000e+00]


ДОДЛЕАТЬ 3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [26]:
np.quantile(arr, .75)

100065.25

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [88]:
print(np.sum(arr[:, 1:2]==0))

arr[:, 1:2][arr[:, 1:2]==0] = 1
arr

479


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [97]:
np.count_nonzero(arr[:, :1])

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [5]:
values, counts = np.unique(arr, return_counts=True)
print(values, counts)

[         0          1          2 ...     537485     537671 2147483647] [ 479  250 1738 ...    1    1    1]


ДОДЕЛАТЬ 7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [28]:
mask = arr[:,2:3] <= 5
arr[mask]
# arr_less_than_six = arr[arr[:,2:3] <= 5]
# print(arr_less_than_six)



IndexError: boolean index did not match indexed array along dimension 1; dimension is 3 but corresponding boolean dimension is 1

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [53]:
np.mean(arr[arr[:, 1].argsort()][-100:, :], axis=0)[1]

21518445.39

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [63]:
arr[np.random.randint(len(arr), size=10)]

array([[282894,     27,      7],
       [208039,    510,     14],
       [490915,    210,     15],
       [116088,     45,     11],
       [238377,     80,     11],
       [197275,     20,      8],
       [183993,     35,      5],
       [ 24253,     35,     12],
       [149610,     25,     12],
       [370940,     55,     18]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [117]:
(np.count_nonzero(arr[:, 2:3] < np.mean(arr, axis=0)[2]) / len(arr)) * 100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [19]:
time = arr[:, 1:2] <= 20
ingredients = arr[:, 2:3] <= 5
arr

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

In [17]:
np.take(arr, np.logical_and(time, ingredients))

array([[127244],
       [127244],
       [127244],
       ...,
       [127244],
       [    60],
       [127244]])

In [15]:
np.logical_and(time, ingredients).shape

array([[False],
       [False],
       [False],
       ...,
       [False],
       [ True],
       [False]])

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [47]:
lst = [0, 1, 2, 5, 10, 47, 92]
lst

[0, 1, 2, 5, 10, 47, 92]

In [48]:
arr = np.array(lst)

In [8]:
arr

array([ 1,  2,  5, 10, 47, 92])

In [11]:
mask = arr % 5 == 0
arr[mask]

array([ 5, 10])

In [14]:
b = np.array([0,1,2,2,0,1]) # берет элементы с индексом 0, 1, 2, 2, 0, 1 из списка arr
arr[b]

array([1, 2, 5, 5, 1, 2])

In [6]:
test_arr = np.arange(20).reshape(5, 4)
np.transpose(test_arr)

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [96]:
test_arr[:, :1]

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16]])

In [38]:
test_arr = np.array(lst)
test_arr%5

array([0, 1, 2, 0, 0, 2, 2], dtype=int32)

In [217]:
mask = arr[:, 2:3] <= 5
# mask.shape
# arr[:, :, mask]
# print(mask)
masked = arr.copy()
# masked[:, mask]
# masked[mask]
# mask = np.c_[np.ones(100000), np.ones(100000), mask]
print(mask)
# masked[np.array(mask)]
masked


[[False]
 [False]
 [False]
 ...
 [False]
 [ True]
 [False]]


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])