# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [1]:
import numpy as np

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
arr = np.random.uniform(0, 20, size=(4, 7))
(arr - arr.min())/ (arr.max() - arr.min())

array([[5.87898845e-01, 1.35817242e-01, 4.89836823e-02, 8.06881916e-01,
        1.90401646e-01, 8.47210342e-01, 2.83742023e-01],
       [7.09155241e-04, 4.14877796e-01, 2.30407933e-01, 9.91921769e-01,
        1.00000000e+00, 4.14177168e-01, 9.52831023e-01],
       [3.32769644e-01, 7.23632014e-01, 8.30542300e-01, 9.07715340e-01,
        3.18374780e-01, 5.72848085e-01, 4.56406731e-01],
       [5.71982388e-01, 1.82057746e-01, 0.00000000e+00, 4.21916857e-01,
        4.34759742e-01, 8.00429494e-01, 9.75707239e-01]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [3]:
matrix = np.random.random_integers(0, high=10, size=(8, 10))
matrix

C:\Users\damir\AppData\Local\Temp/ipykernel_13052/1159314955.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  matrix = np.random.random_integers(0, high=10, size=(8, 10))


array([[ 4,  8,  9,  0,  2,  7, 10,  2, 10,  5],
       [ 2,  2,  0,  9,  1,  6,  4,  6,  9,  9],
       [ 9,  2,  2,  4,  3,  9,  0,  5,  6,  0],
       [10,  8,  7,  7,  8,  8,  7,  3,  0,  1],
       [ 7,  1,  2,  7,  2,  9,  9,  4,  8,  8],
       [10,  6,  5,  2,  9,  1,  4, 10,  9,  4],
       [ 7,  8,  0,  6,  7,  2,  5,  6,  3,  1],
       [ 7,  8,  6,  3,  5,  7,  9,  9,  2,  8]])

In [4]:
sum_of_rows = matrix.sum(axis=1)

print(np.argmin(sum_of_rows))
matrix[np.argmin(sum_of_rows)]

2


array([9, 2, 2, 4, 3, 9, 0, 5, 6, 0])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [5]:
vector1 = np.random.rand(3,1)
vector1

array([[0.99152202],
       [0.88360489],
       [0.96848263]])

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [6]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
minus_C = C * -1
transpose_A = np.transpose(A)
transpose_B = np.transpose(B)
out = transpose_A @ minus_C @ transpose_B
out

array([[ 135,  185],
       [ -25, -100],
       [ -70, -220]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

In [7]:
arr = np.loadtxt("data/minutes_n_ingredients.csv", dtype='int32', skiprows=1, delimiter=",")
print(arr[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [8]:
mean = np.mean(arr, axis=0)
print(mean)

minimum = arr.min(axis=0)
print(minimum)

maximum = arr.max(axis=0)
print(maximum)

median = np.median(arr, axis=0)
print(median)

[2.22064324e+05 2.16010017e+04 9.05528000e+00]
[38  0  1]
[    537671 2147483647         39]
[2.071935e+05 4.000000e+01 9.000000e+00]


 3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [9]:
quantile = np.quantile(arr[:, 1], .75)
arr[:, 1] = np.where(arr[:, 1] > quantile, quantile, arr[:, 1])
arr

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [10]:
print(np.sum(arr[:, 1:2] == 0))

arr[:, 1:2][arr[:, 1:2] == 0] = 1
arr

479


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [11]:
# np.count_nonzero(arr[:, :1])
np.shape(arr)[0]

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [12]:
values, counts = np.unique(arr, return_counts=True)
print(values, counts)

[     1      2      3 ... 537458 537485 537671] [ 729 1738 3358 ...    1    1    1]


 7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [13]:
arr_copy_lower_then5 = arr.copy()
mask = arr_copy_lower_then5[:, 2] <= 5
arr_copy_lower_then5[mask]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [14]:
arr_copy = arr.copy().astype(np.float32)
values = arr_copy[:, 2] / arr_copy[:, 1]
arr_copy = np.insert(arr_copy, 3, values, axis = 1)
arr_copy

array([[1.2724400e+05, 6.0000000e+01, 1.6000000e+01, 2.6666668e-01],
       [2.3891000e+04, 2.5000000e+01, 7.0000000e+00, 2.8000000e-01],
       [9.4746000e+04, 1.0000000e+01, 6.0000000e+00, 6.0000002e-01],
       ...,
       [4.9843200e+05, 6.5000000e+01, 1.5000000e+01, 2.3076923e-01],
       [3.7091500e+05, 5.0000000e+00, 4.0000000e+00, 8.0000001e-01],
       [8.1993000e+04, 6.5000000e+01, 1.4000000e+01, 2.1538462e-01]],
      dtype=float32)

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [15]:
np.mean(arr[arr[:, 1].argsort()][-100:, :], axis=0)[2]

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [16]:
arr[np.random.randint(len(arr), size=10)]

array([[416412,     35,     10],
       [ 45374,     30,      9],
       [415175,     50,      9],
       [113048,     65,     12],
       [300703,     10,      6],
       [356712,     60,     12],
       [215631,     65,      8],
       [ 24783,      5,      4],
       [ 32796,     40,     10],
       [242162,      2,      4]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [17]:
(np.count_nonzero(arr[:, 2:3] < np.mean(arr, axis=0)[2]) / len(arr)) * 100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [18]:
arr_copy = arr.copy()
arr_copy = np.c_[ arr_copy, np.zeros(len(arr_copy), dtype=int)]
condition = (arr_copy[:, 1:2] <= 20) & (arr_copy[:, 2:3] <= 5)
arr_copy[:, 3:4] = np.where(condition, 1, arr_copy[:, 3:4])
arr_copy

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [19]:
f"{round(np.sum(arr_copy[:, 3:4])/len(arr_copy), 3) * 100}%"

'9.6%'

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [38]:
arr_copy = arr.copy()
short = arr_copy[arr_copy[:, 1] < 10]

condition = (10 <= arr_copy[:, 1]) & (arr_copy[:, 1] < 20)\
medium = arr_copy[condition]

long = arr_copy[arr_copy[:, 1] > 20]

out_array = np.array((short, medium, long), dtype=object)
out_array

array([array([[ 67660,      5,      6],
              [366174,      7,      9],
              [204134,      5,      3],
              ...,
              [420725,      5,      3],
              [  4747,      1,      9],
              [370915,      5,      4]]),
       array([[ 94746,     10,      6],
              [ 33941,     18,      9],
              [446597,     15,      5],
              ...,
              [ 44120,     17,      5],
              [ 60756,     15,      5],
              [128811,     15,      4]]),
       array([[127244,     60,     16],
              [ 23891,     25,      7],
              [157911,     60,     14],
              ...,
              [287943,     65,     15],
              [498432,     65,     15],
              [ 81993,     65,     14]])], dtype=object)